Repository epsagon/epsagon-dotnet, pull requests merged in 2020-10, with the labels that each got.

#19 fix(general-handler): sending trace on finish
  src/Epsagon.Dotnet.Lambda/EpsagonGeneralHandler.cs
Labels: size/XS

#18 feat(lambda): add getTraceUrl function to EpsagonHandler
  src/Epsagon.Dotnet.Instrumentation/EpsagonUtils.cs
  src/Epsagon.Dotnet.Lambda/EpsagonHandler.cs
  src/Epsagon.Dotnet.Lambda/LambdaTriggerHandler.cs
Labels: size/M

#20 Feature/getting trace url for legacy traces/ep 4685
  README.md
  src/Epsagon.Dotnet.Instrumentation/EpsagonUtils.cs
  src/Epsagon.Dotnet.Lambda/EpsagonGeneralHandler.cs
  src/Epsagon.Dotnet.Lambda/LambdaTriggerHandler.cs
  src/Epsagon.Dotnet.Mvc/EpsagonMvcHandler.cs
  src/Epsagon.Dotnet.Tracing.Legacy/EpsagonConverter.cs
Labels: size/M

#21 feat(adonet): added support for ado.net based db instrumentation
  src/Epsagon.Dotnet.Core/Configuration/ConfigurationService.cs
  src/Epsagon.Dotnet.Core/Configuration/EpsagonConfiguration.cs
  src/Epsagon.Dotnet.Core/Configuration/IEpsagonConfiguration.cs
  src/Epsagon.Dotnet.Core/Utils.cs
  src/Epsagon.Dotnet.Instrumentation/ADONET/ADONETEpsagonExtensions.cs
  src/Epsagon.Dotnet.Instrumentation/ADONET/EpsagonTracedCommand.cs
  src/Epsagon.Dotnet.Instrumentation/ADONET/EpsagonTracedConnection.cs
  src/Epsagon.Dotnet.Lambda/EpsagonGeneralHandler.cs
  src/Epsagon.Dotnet.Tracing.Legacy/EpsagonConverter.cs
  src/Epsagon.Dotnet.Tracing.Legacy/TraceSenders/HTTPTraceSender.cs
Labels: size/L

#22 feat(adonet): added table_name extraction from sql statements
  src/Epsagon.Dotnet.Instrumentation/ADONET/EpsagonTracedCommand.cs
  src/Epsagon.Dotnet.Instrumentation/ADONET/TableNameExtractor.cs
Labels: size/M

#23 chore(ci-build): adding initial github workflow
  .github/workflows/merge-publish.yml
  .github/workflows/pr-build.yml
  .releaserc
  src/Epsagon.Dotnet.Core/Epsagon.Dotnet.Core.csproj
  src/Epsagon.Dotnet.Instrumentation/Epsagon.Dotnet.Instrumentation.csproj
  src/Epsagon.Dotnet.Lambda/Epsagon.Dotnet.Lambda.csproj
  src/Epsagon.Dotnet.Mvc/Epsagon.Dotnet.Mvc.csproj
  src/Epsagon.Dotnet.Tracing.Legacy/Epsagon.Dotnet.Tracing.Legacy.csproj
  src/Epsagon.Dotnet.Tracing.OpenTracingJaeger/Epsagon.Dotnet.Tracing.OpenTracingJaeger.csproj
Labels: size/L

#24 chore(ci-build): fixed publish action
  .github/workflows/merge-publish.yml
Labels: size/XS

#26 feat(ef-core-inst): instrumenting efcore commands
  src/Epsagon.Dotnet.Instrumentation/EFCore/EFCoreEpsagonExtensions.cs
  src/Epsagon.Dotnet.Instrumentation/EFCore/EpsagonCommandInterceptor.cs
  src/Epsagon.Dotnet.Instrumentation/Epsagon.Dotnet.Instrumentation.csproj
Labels: size/M

#27 chore(docs): added efcore example + readme
  README.md
  examples/epsagon-ef-core/Program.cs
  examples/epsagon-ef-core/ef-core-trace.csproj
Labels: size/M

#28 chore(ci-build): updated release steps
  .github/workflows/merge-publish.yml
  .releaserc
  scripts/prepare.sh
  scripts/publish.sh
Labels: size/M

#29 refactor(bootstrap): added option to pass config using EpsagonBootstrap
  .github/workflows/merge-publish.yml
  src/Epsagon.Dotnet.Instrumentation/EpsagonBootstrap.cs
Labels: size/S
