Repository epsagon/epsagon-dotnet, pull requests merged in 2020-09, with the labels that each got.

#14 Adding sns sqs example
  examples/sns-sqs-lambda/.gitignore
  examples/sns-sqs-lambda/Handler.cs
  examples/sns-sqs-lambda/aws-csharp.csproj
  examples/sns-sqs-lambda/build.cmd
  examples/sns-sqs-lambda/build.sh
  examples/sns-sqs-lambda/serverless.yml
  scripts/publish-all.sh
  src/Epsagon.Dotnet.Core/Epsagon.Dotnet.Core.csproj
  src/Epsagon.Dotnet.Instrumentation/ElasticSearch/ElasticSearchEventsHandler.cs
  src/Epsagon.Dotnet.Instrumentation/Epsagon.Dotnet.Instrumentation.csproj
  src/Epsagon.Dotnet.Instrumentation/Handlers/SNS/Operations/PublishRequestHandler.cs
  src/Epsagon.Dotnet.Instrumentation/TriggerFactory.cs
  src/Epsagon.Dotnet.Instrumentation/Triggers/SNSLambda.cs
  src/Epsagon.Dotnet.Instrumentation/Triggers/SQSLambda.cs
  src/Epsagon.Dotnet.Mvc/Epsagon.Dotnet.Mvc.csproj
  src/Epsagon.Dotnet.Tracing.Legacy/Epsagon.Dotnet.Tracing.Legacy.csproj
  src/Epsagon.Dotnet.Tracing.OpenTracingJaeger/Epsagon.Dotnet.Tracing.OpenTracingJaeger.csproj
  src/Epsagon.Dotnet.Tracing.OpenTracingJaeger/JaegerTracer.cs
Labels: size/XL

#15 fixing sns -> sqs connection
  examples/sns-sqs-lambda/serverless.yml
  src/Epsagon.Dotnet.Instrumentation/Triggers/SQSLambda.cs
Labels: size/XS

#16 feat(SNS+SQS): fixing triggers and interconnectivity
  examples/sns-sqs-lambda/serverless.yml
Labels: size/XS

#17 [EP-4578] Adding Generic Function to docs
  README.md
Labels: size/S
